Class ShotgunCasing5HASG : Actor
{
		override void BeginPlay(void)
	{
		ChangeStatNum(STAT_PB_BULLETS);
		NashGoreStatics.QueueCasings();
		Super.BeginPlay();
	}
   Default
   {Height 12;
   Radius 9;
   Speed 6;
   Scale 0.15;
   +DOOMBOUNCE;
   - NOGRAVITY;
   +WINDTHRUST;
   +CLIENTSIDEONLY;
   +MOVEWITHSECTOR;
   +MISSILE;
   +NOBLOCKMAP;
   -DROPOFF;
   +NOTELEPORT;
   +FORCEXYBILLBOARD;
   +NOTDMATCH;
   +GHOST;
   +ROLLSPRITE;
   Mass 1;
   SeeSound "weapons/shell";
   }
   States
   {
    Spawn:
      TNT1 A 0;
	  
	  Exist:
	  TNT1 A 0 A_JumpIfInventory("Zoomed",1,"ShellSpin");
      TNT1 A 0 A_SetRoll(roll + (20),SPF_INTERPOLATE);
	  CAS8 G 1;
	 ShellSpin:
	  CAS8 G 1 
	  {
	  A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  }
	  TNT1 A 0 A_SetRoll(roll - (10),SPF_INTERPOLATE);
	  TNT1 A 0 A_JumpIf(waterlevel > 1, "Disappear");
	  Goto ShellSpin;
   Death:
      TNT1 A 0 A_SetRoll(0,SPF_INTERPOLATE);
	  LCPJ A 0 A_Jump(256,"Rest1","Rest2","Rest3","Rest4","Rest5","Rest6","Rest7","Rest8");
      Goto Rest1;
    Rest1:
	  CAS8 IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest1Dead:
      CAS8 I 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest2:
	  CAS8 JJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest2Dead:
      CAS8 J 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest3:
	  CAS8 KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest3Dead:
      CAS8 K 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest4:
	  CAS8 LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest4Dead:
      CAS8 L 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest5:
	  CAS8 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest5Dead:
      CAS8 M 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest6:
	  CAS8 IIIIIIIIIIIIIIIIIIIIIIIIIII 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest2Dead:
      CAS8 I 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest7:
	  CAS8 JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest7Dead:
      CAS8 J 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest8:
	  CAS8 KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest8Dead:
      CAS8 K 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
	  loop;
	  
	  Disappear:
	  TNT1 A 1;
	  Stop;
   }
}

Class ExplosiveCasingHASG : Actor
{
		override void BeginPlay(void)
	{
		ChangeStatNum(STAT_PB_BULLETS);
		NashGoreStatics.QueueCasings();
		Super.BeginPlay();
	}
   Default
   {Height 12;
   Radius 9;
   Speed 6;
   Scale 0.15;
   +DOOMBOUNCE;
   - NOGRAVITY;
   +WINDTHRUST;
   +CLIENTSIDEONLY;
   +MOVEWITHSECTOR;
   +MISSILE;
   +NOBLOCKMAP;
   -DROPOFF;
   +NOTELEPORT;
   +FORCEXYBILLBOARD;
   +NOTDMATCH;
   +GHOST;
   +ROLLSPRITE;
   Mass 1;
   SeeSound "weapons/shell";
   }
   States
   {
    Spawn:
      TNT1 A 0;
	  
	  Exist:
	  TNT1 A 0 A_JumpIfInventory("Zoomed",1,"ShellSpin");
      TNT1 A 0 A_SetRoll(roll + (20),SPF_INTERPOLATE);
	  WCS1 G 1;
	 ShellSpin:
	  WCS1 G 1 
	  {
	  A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  }
	  TNT1 A 0 A_SetRoll(roll - (10),SPF_INTERPOLATE);
	  TNT1 A 0 A_JumpIf(waterlevel > 1, "Disappear");
	  Goto ShellSpin;
   Death:
      TNT1 A 0 A_SetRoll(0,SPF_INTERPOLATE);
	  LCPJ A 0 A_Jump(256,"Rest1","Rest2","Rest3","Rest4","Rest5","Rest6","Rest7","Rest8");
      Goto Rest1;
    Rest1:
	  WCS1 IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest1Dead:
      WCS1 I 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest2:
	  WCS1 JJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest2Dead:
      WCS1 J 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest3:
	  WCS1 KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest3Dead:
      WCS1 K 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest4:
	  WCS1 LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest4Dead:
      WCS1 L 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest5:
	  WCS1 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest5Dead:
      WCS1 M 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest6:
	  WCS1 IIIIIIIIIIIIIIIIIIIIIIIIIII 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest2Dead:
      WCS1 I 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest7:
	  WCS1 JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest7Dead:
      WCS1 J 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest8:
	  WCS1 KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest8Dead:
      WCS1 K 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
	  loop;
	  
	  Disappear:
	  TNT1 A 1;
	  Stop;
   }
}
Class DanmakuCasingHASG : Actor
{
		override void BeginPlay(void)
	{
		ChangeStatNum(STAT_PB_BULLETS);
		NashGoreStatics.QueueCasings();
		Super.BeginPlay();
	}
   Default
   {Height 12;
   Radius 9;
   Speed 6;
   Scale 0.15;
   +DOOMBOUNCE;
   - NOGRAVITY;
   +WINDTHRUST;
   +CLIENTSIDEONLY;
   +MOVEWITHSECTOR;
   +MISSILE;
   +NOBLOCKMAP;
   -DROPOFF;
   +NOTELEPORT;
   +FORCEXYBILLBOARD;
   +NOTDMATCH;
   +GHOST;
   +ROLLSPRITE;
   Mass 1;
   SeeSound "weapons/shell";
   }
   States
   {
    Spawn:
      TNT1 A 0;
	  
	  Exist:
	  TNT1 A 0 A_JumpIfInventory("Zoomed",1,"ShellSpin");
      TNT1 A 0 A_SetRoll(roll + (20),SPF_INTERPOLATE);
	  DC0S G 1;
	 ShellSpin:
	  DC0S G 1 
	  {
	  A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  }
	  TNT1 A 0 A_SetRoll(roll - (10),SPF_INTERPOLATE);
	  TNT1 A 0 A_JumpIf(waterlevel > 1, "Disappear");
	  Goto ShellSpin;
   Death:
      TNT1 A 0 A_SetRoll(0,SPF_INTERPOLATE);
	  DC0S A 0 A_Jump(256,"Rest1","Rest2","Rest3","Rest4","Rest5","Rest6","Rest7","Rest8");
      Goto Rest1;
    Rest1:
	  DC0S IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest1Dead:
      DC0S I 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest2:
	  DC0S JJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest2Dead:
      DC0S J 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest3:
	  DC0S KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest3Dead:
      DC0S K 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest4:
	  DC0S LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest4Dead:
      DC0S L 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest5:
	  DC0S MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest5Dead:
      DC0S M 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest6:
	  DC0S IIIIIIIIIIIIIIIIIIIIIIIIIII 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest2Dead:
      DC0S I 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest7:
	  DC0S JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest7Dead:
      DC0S J 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest8:
	  DC0S KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest8Dead:
      DC0S K 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
	  loop;
	  
	  Disappear:
	  TNT1 A 1;
	  Stop;
   }
}

Class WPhosphorusCasingHASG : Actor
{
		override void BeginPlay(void)
	{
		ChangeStatNum(STAT_PB_BULLETS);
		NashGoreStatics.QueueCasings();
		Super.BeginPlay();
	}
   Default
   {Height 12;
   Radius 9;
   Speed 6;
   Scale 0.15;
   +DOOMBOUNCE;
   - NOGRAVITY;
   +WINDTHRUST;
   +CLIENTSIDEONLY;
   +MOVEWITHSECTOR;
   +MISSILE;
   +NOBLOCKMAP;
   -DROPOFF;
   +NOTELEPORT;
   +FORCEXYBILLBOARD;
   +NOTDMATCH;
   +GHOST;
   +ROLLSPRITE;
   Mass 1;
   SeeSound "weapons/shell";
   }
   States
   {
    Spawn:
      TNT1 A 0;
	  
	  Exist:
	  TNT1 A 0 A_JumpIfInventory("Zoomed",1,"ShellSpin");
      TNT1 A 0 A_SetRoll(roll + (20),SPF_INTERPOLATE);
	  WCS1 G 1;
	 ShellSpin:
	  WCS1 G 1 
	  {
	  A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  }
	  TNT1 A 0 A_SetRoll(roll - (10),SPF_INTERPOLATE);
	  TNT1 A 0 A_JumpIf(waterlevel > 1, "Disappear");
	  Goto ShellSpin;
   Death:
      TNT1 A 0 A_SetRoll(0,SPF_INTERPOLATE);
	  LCPJ A 0 A_Jump(256,"Rest1","Rest2","Rest3","Rest4","Rest5","Rest6","Rest7","Rest8");
      Goto Rest1;
    Rest1:
	  WCS1 IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest1Dead:
      WCS1 I 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest2:
	  WCS1 JJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest2Dead:
      WCS1 J 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest3:
	  WCS1 KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest3Dead:
      WCS1 K 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest4:
	  WCS1 LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest4Dead:
      WCS1 L 900;
	  TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest5:
	  WCS1 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest5Dead:
      WCS1 M 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest6:
	  WCS1 IIIIIIIIIIIIIIIIIIIIIIIIIII 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest2Dead:
      WCS1 I 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest7:
	  WCS1 JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest7Dead:
      WCS1 J 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
      loop;
    Rest8:
	  WCS1 KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
	  Rest8Dead:
      WCS1 K 900;
	 TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("ToggleBulletJanitor")==1,"Disappear");
	  loop;
	  
	  Disappear:
	  TNT1 A 1;
	  Stop;
   }
}

Class ShotCaseSpawnHASG5 : RifleCaseSpawn
{
	States
	{
	Spawn:
	    TNT1 A 0 ;
		//TNT1 A 1 A_SpawnProjectile("ShotgunCasing5HASG",0,0,random(-80,-100),CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH,random(40,60));
		TNT1 A 1 A_SpawnItemEX("ShotgunCasing5HASG",0,0,-7,frandom(3,5),frandom(3,4),frandom(8,11));
		Stop;
	}
}

Class ShotCaseSpawnHASGEXP : RifleCaseSpawn
{
	States
	{
	Spawn:
	    TNT1 A 0 ;
		//TNT1 A 1 A_SpawnProjectile("ExplosiveCasingHASG",0,0,random(-80,-100),CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH,random(40,60));
		TNT1 A 1 A_SpawnItemEX("ExplosiveCasingHASG",0,0,-7,frandom(3,5),frandom(3,4),frandom(8,11));
		Stop;
	}
}

Class ShotCaseSpawnHASGDAN : RifleCaseSpawn
{
	States
	{
	Spawn:
	    TNT1 A 0 ;
		//TNT1 A 1 A_SpawnProjectile("DanmakuCasingHASG",0,0,random(-80,-100),CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH,random(40,60));
		TNT1 A 1 A_SpawnItemEX("DanmakuCasingHASG",0,0,-7,frandom(3,5),frandom(3,4),frandom(8,11));
		Stop;
	}
}

Class ShotCaseSpawnHASGWP : RifleCaseSpawn
{
	States
	{
	Spawn:
	    TNT1 A 0 ;
		//TNT1 A 1 A_SpawnProjectile("WPhosphorusCasingHASG",0,0,random(-80,-100),CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH,random(40,60));
		TNT1 A 1 A_SpawnItemEX("WPhosphorusCasingHASG",0,0,-7,frandom(3,5),frandom(3,4),frandom(8,11));
		Stop;
	}
}

//Some of missing Chance and more...


class GolideExplosiveProjectile : PB_Projectile
{
	Default
	{
		radius 3;
		height 3;
		Speed 400;
		DamageType "Explosive";
		Gravity 1;
		Scale 0.1;
		Decal "Scorch";
		SeeSound "weapons/RLL";
		Obituary "$OB_MPROCKET";
		+nogravity;
		damage 12;
		damagetype "ExplosiveImpact";
		PB_Projectile.BaseDamage 20;
		PB_Projectile.RipperCount 0;
	}
	
	States
	{
		Spawn:
			TNT1 A 1;
		Fly:
			DBAC A 1 bright Light("ROCKET")
			{
				if(waterlevel < 1) {
					spawnFirespark(pos);
					//A_SpawnItemEx("RocketTrailSparks",-10,0,0,-5,0,0);
				}
			}
			loop;
		Crash:
		XDeath:
		Death:
			TNT1 A 0;
			TNT1 A 0
			{
				A_Explode(60,128,XF_HURTSOURCE|RTF_THRUSTZ, 0, 64);
				A_StopSound(105);
				A_StartSound("FAREXPL", CHAN_AUTO,CHANF_OVERLAP,0.5,0,1.1);
				A_QuakeEx (2,2,2,4,0,100,"");
				A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnItemEx ("LiquidExplosionEffectSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				A_SpawnProjectile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
				A_Spawnprojectile ("FireworkSFXType2", 0, 0, random (0, 360), 2, random (-60, -30));
				A_SpawnProjectile ("MediumExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
				A_SpawnProjectile ("PBExplosionparticles", 0, 0, random (0, 360), 2, random (40, 90));
				A_SpawnProjectile ("PBExplosionparticles2", 0, 0, random (0, 360), 2, random (40, 90));
				A_SpawnProjectile ("PBExplosionparticles3", 10, 0, random (0, 360), 2, random (40, 90));
			}
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			X004 ABCDE 1 bright Light("EXPLOSIONFLASH");
			X004 FGHIJKLMNOPQ 1 bright;
			stop;
		Spawn2:
			X003 ABCDE 1 bright Light("EXPLOSIONFLASH");
			X003 FGHIJKLMNOPQRSTUVWXYZ 1 bright;
			stop;
		Spawn3:
			X125 ABCDE 1 bright Light("EXPLOSIONFLASH");
			X125 FGHIJKLMNOPQR 1 bright;
			Stop;
	}
	
	void spawnFirespark(vector3 position)
	{
		FSpawnParticleParams DBSPK;
		DBSPK.Texture = TexMan.CheckForTexture("REXPA0");
		DBSPK.Color1 = "FFFFFF";//"FF8400";
		DBSPK.Style = STYLE_ADD;
		DBSPK.Flags = SPF_ROLL|SPF_FULLBRIGHT;
		DBSPK.Vel = (frandom(-5,5),frandom(-5,5),frandom(-5,5)); 
		DBSPK.Startroll = random(0,360);
		DBSPK.RollVel = frandom(-15,15);
		DBSPK.StartAlpha = 0.85;
		//DBSPK.FadeStep = 0.1;
		DBSPK.Size = random(12,26);
		DBSPK.SizeStep = -2;
		DBSPK.Lifetime = random(4,8); 
		DBSPK.Pos = position;
		Level.SpawnParticle(DBSPK);
	}
}

class HMGExplosiveProjectile : GolideExplosiveProjectile
{
	Default
	{
		radius 3;
		height 3;
		Speed 400;
		DamageType "Explosive";
		Gravity 1;
		Scale 0.1;
		Decal "Scorch";
		SeeSound "weapons/RLL";
		Obituary "$OB_MPROCKET";
		+nogravity;
		damage 50;
		damagetype "ExplosiveImpact";
		PB_Projectile.BaseDamage 50;
		PB_Projectile.RipperCount 0;
	}
}

Class WPhosphorusProjectile_Golide : PB_Projectile
{
	default
	{
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		damagefunction (15*frandom(2.0,3.0));
		PB_Projectile.BaseDamage 32;
		PB_Projectile.RipperCount 0;
		Decal "SmallerScorch";
		PROJECTILE;
		gravity 0.6;
		DamageType "Fire";
		PoisonDamageType "Fire";
		PoisonDamage 7;
		+ADDITIVEPOISONDURATION;
		renderstyle "add";
		radius 2;
		height 2;
		speed 200;
		alpha 0.95;
		scale 0.45;
	}
	states
	{
		Spawn:
			DBAC A 1 BRIGHT spawnflameFlare(pos);
			//TNT1 A 0 A_SpawnItemEx("ShotgunParticles", random(8,-8), random(8,-8), random(8,-8), 0, 0, 0, 0, 128, 0);
			//TNT1 A 0 A_SpawnItemEx("ExplosionParticleVerySlow", random(8,-8), random(8,-8), random(19,-19), 0, 0, 0, 0, 128, 0);
			Loop;
		/*XDeath:
		Crash:
		Death:
			TNT1 A 0 A_Explode(10,36);
			TNT1 A 1;
			TNT1 A 0 A_SpawnWPSmoke(pos);//A_spawnitem("WhitePSmokeFx_SP");
			TNT1 A 0 A_spawnitem("WPShockWave");
			TNT1 AAAAAA 0 A_spawnitemEx("BigFlamesIG_SP",random(-15,15),random(-15,15),random(-5,5),0,0,0,0,SXF_NOCHECKPOSITION);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_startSound("FAREXPL",3);
			stop;*/
	}
	
	bool ticked;
	override void Tick()
	{
		super.tick();
		if(isfrozen())
			return;
		if(!ticked)
			ticked = true;
		else
			SpawnFlameTrail(pos);
	}
	
	override void effect()
	{
		if(ticked)
			SpawnFlameTrail(pos);
	}
	
	override void OnHitActor(Actor target, Name dmgType)
	{
		if(pos.z < floorz)
			SetZ(floorz);
		A_Explode(10,36);
		A_SpawnWPSmoke(pos);
		for(int i = 0; i < random(3,6); i++)
			A_spawnitemEx("BigFlamesIG_SP",random(-15,15),random(-15,15),random(-5,5),0,0,0,0,SXF_NOCHECKPOSITION);
		spawnflameFlare(pos,true);
		A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		A_startSound("FAREXPL",3);
	}
	override void OnExplode(int type)
	{
		if(pos.z < floorz)
			SetZ(floorz);
		A_Explode(10,36);
		A_SpawnWPSmoke(pos);
		for(int i = 0; i < random(3,6); i++)
			A_spawnitemEx("BigFlamesIG_SP",random(-15,15),random(-15,15),random(-5,5),0,0,0,0,SXF_NOCHECKPOSITION);
		spawnflameFlare(pos,true);
		A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		A_startSound("FAREXPL",3);
	}
	
	void A_SpawnWPSmoke(vector3 position)
	{
		FSpawnParticleParams PFSMK;
		PFSMK.Texture = TexMan.CheckForTexture ("X103E0");
		PFSMK.Color1 = "FFFFFF";
		PFSMK.Style = STYLE_Add;
		PFSMK.Flags = SPF_ROLL;
		PFSMK.Vel = (frandom(-2.5,2.5),frandom(-2.5,2.5),frandom(-2.3,2.3)); 
		PFSMK.Startroll = random(0,360);
		PFSMK.RollVel = frandom(-10,10);
		PFSMK.StartAlpha = 0.75;
		PFSMK.FadeStep = 0.1;
		PFSMK.Size = frandom(45,60);
		PFSMK.SizeStep = 6;
		PFSMK.Lifetime = FRandom(10,12); 
		PFSMK.Pos = position;
		Level.SpawnParticle(PFSMK);
	}
	
	void spawnflameFlare(vector3 position, bool bigger = false)
	{
		FSpawnParticleParams FFLAR;
		FFLAR.Texture = TexMan.CheckForTexture("FSO1A0");
		FFLAR.Color1 = "FFFFFF";
		FFLAR.Style = STYLE_ADD;
		FFLAR.Flags = SPF_ROLL|SPF_FULLBRIGHT;
		FFLAR.Vel = (0,0,0);
		FFLAR.Startroll = random(0,360);
		FFLAR.RollVel = frandom(-3,3);
		FFLAR.StartAlpha = 0.85;
		FFLAR.FadeStep = bigger ? 0.15 : 0.25;
		FFLAR.Size = random(100,120);
		FFLAR.SizeStep = 10;
		FFLAR.Lifetime = bigger ? random(3,6): 1; 
		FFLAR.Pos = position;
		Level.SpawnParticle(FFLAR);
	}
	
	void SpawnFlameTrail(vector3 position, bool small = false)
	{
		FSpawnParticleParams FTrail;
		string txt = "EXP7D0";
		int f = random(1,6);
		switch(f)
		{
			case 1:		txt = "EXP7D0";			break;
			case 2:		txt = "EXP8D0";			break;
			case 3:		txt = "EXP2A0";			break;
			case 4:		txt = "EXP0D0";			break;
			case 5:		txt = "EXP9C0";			break;
			case 6:		txt = "EXP6D0";			break;
		}
		FTrail.Texture = TexMan.CheckForTexture(txt);//("DB54K0");
		FTrail.Color1 = "FFFFFF";
		FTrail.Style = STYLE_ADD;
		FTrail.Flags = SPF_ROLL|SPF_FULLBRIGHT;
		FTrail.Vel = (frandom(-1.5,1.5),frandom(-1.5,1.5),frandom(-1.5,1.5)); 
		FTrail.Startroll = random(0,360);
		FTrail.RollVel = frandom(-5,5);
		FTrail.StartAlpha = 1.0;
		FTrail.FadeStep = 0.30;
		FTrail.Size = random(55,72);
		FTrail.SizeStep = -random(4,7);
		FTrail.Lifetime = random(2,3); 
		FTrail.Pos = position;
		Level.SpawnParticle(FTrail);
	}
}

//
//	well, in real life white phosphorous reacts a lot with oxygen and produces a lot of smoke
//
Class BigFlamesIG_SP : FT_GroundFireSpawner
{
	int lifetime;
	Default
	{
		damagetype "Fire";
		renderstyle "add";
		damage 1;
		+nodamagethrust;
		+floorclip;
		scale 0.8;
		+bright;
	}
	
	states
	{
		spawn:
			TNT1 A 0 SpawnWPSmoke(pos + (0,0,random(28,36)));
			TNT1 A 0 spawnphosphorusFlare(pos + (0,0,6));
			FLME ABCDEFG 1 {
				if(random(0,1) == 1)
					A_explode(3,180,XF_NOSPLASH|XF_HURTSOURCE);
			}
			TNT1 A 0 SpawnWPSmoke(pos + (0,0,random(28,36)));
			TNT1 A 0 spawnphosphorusFlare(pos + (0,0,6));
			TNT1 A 0 SpawnParticleFast();
			FLME HIJKLM 1 {
				if(random(0,1) == 1)
					A_explode(3,180,XF_NOSPLASH|XF_HURTSOURCE);
			}
			TNT1 A 0 SpawnWPSmoke(pos + (0,0,random(28,36)));
			FLME N 1 {
				SpawnParticleFast();
				lifetime--;
			}
			TNT1 A 0 A_jumpif(lifetime <= 0 || waterlevel > 0,"Fadening");
			loop;
		Fadening:
			TNT1 A 0 spawnphosphorusFlare(pos + (0,0,6),true);
			FLME ABCDEFGHIJKLMN 1 {
				A_Fadeout(0.1);
				A_setscale(self.scale.x - frandom(0.02,0.07));
			}
			loop;
	}
	
	string flarcol;
	
	override void beginplay()
	{
		lifetime = random(7,35);
		bXFLIP = random(0,1);
		A_Setscale(self.scale.x + frandom(-0.2,0.2));
		flarcol = "LENYA0";
		switch(random(1,6))
		{
			case 1: flarcol = "LENYA0";	break;
			case 2: flarcol = "LENRA0";	break;
			case 3: flarcol = "LEYSO0";	break;
			case 4: flarcol = "L2NYA0";	break;	
			case 5: flarcol = "FLARA0";	break;
			case 6: flarcol = "DBFLA0";	break;
		}
		super.beginplay();
	}
	
	void SpawnWPSmoke(vector3 position)
	{
		if(pb_performance_fire)
			return;
		FSpawnParticleParams PFSMK;
		PFSMK.Texture = TexMan.CheckForTexture("X103E0");
		PFSMK.Color1 = "FFFFFF";
		PFSMK.Style = STYLE_ADD;
		PFSMK.Flags = SPF_ROLL;
		PFSMK.Vel = (frandom(-1.0,1.0),frandom(-1.0,1.0),frandom(2.75,10.5)); 
		PFSMK.Startroll = random(0,360);
		PFSMK.RollVel = frandom(-10,10);
		PFSMK.StartAlpha = 0.25;
		PFSMK.Size = frandom(60,70);
		PFSMK.SizeStep = 6;
		PFSMK.Lifetime = FRandom(9,15);
		PFSMK.FadeStep = PFSMK.StartAlpha / PFSMK.Lifetime;
		PFSMK.Pos = position;
		Level.SpawnParticle(PFSMK);
	}
	
	void spawnphosphorusFlare(vector3 position, bool dying = false)
	{
		FSpawnParticleParams FFLAR;
		FFLAR.Texture = TexMan.CheckForTexture(flarcol);
		FFLAR.Color1 = "FFFFFF";
		FFLAR.Style = STYLE_ADD;
		FFLAR.Flags = SPF_ROLL|SPF_FULLBRIGHT;
		FFLAR.Vel = (0,0,0);
		FFLAR.Startroll = random(0,360);
		FFLAR.RollVel = frandom(-3,3);
		FFLAR.StartAlpha = 0.25;
		FFLAR.FadeStep = dying ? 0.03 : 0;
		FFLAR.Size = random(140,150);
		FFLAR.SizeStep = dying ? -0.25 : 0;
		FFLAR.Lifetime = 7; 
		FFLAR.Pos = position;
		Level.SpawnParticle(FFLAR);
	}
	
}

Class WhitePSmokeFx_SP : Actor
{
	default
	{
		renderstyle "add";
		Translation "0:255=%[0,0,0]:[1.0,1.0,1.0]";
		Scale 0.15;
		Alpha 0.75;
	}
	states
	{
		Spawn:
			TNT1 A 0 nodelay A_jump(256,1,3,5,7,9,11,13,15);
			X102 AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQRRSSTTUUVV 1 {
				A_fadeout(0.05);
				A_setscale(self.scale.x + frandom(0.05,0.07));
			}
			stop;
	}
	override void beginplay()
	{
		bXFLIP = random(0,1);
		super.beginplay();
	}
}

Class WPShockWave_SP : Actor
{
	default
	{
		Translation "0:255=%[0,0,0]:[1.0,1.0,1.0]";
		renderstyle "add";
		//+bright;
		Scale 0.44;
		+nointeraction;
	}
	states
	{
		Spawn:
			X060 A 1 {
				A_fadeout(0.1);
				A_setscale(self.scale.x + frandom(0.06,0.1));
			}
			loop;
	}
}


Class DarkDanmakuProjectile : Actor
{
	default
	{
		projectile;
		speed 80;
		+doombounce;
		bouncecount 3;
		radius 5;
		height 5;
		projectilekickback 900;
		damage (10);
		renderstyle "add";
		+CANBOUNCEWATER;
		+BOUNCEAUTOOFF;
		+USEBOUNCESTATE;
		+bright;
		+forcexybillboard;
		+rollsprite;
		+FORCERADIUSDMG;
		damagetype "plasma";
	}
	
	color tracercolor;
	
	states
	{
		Spawn:
			TPEL A 1 nodelay A_Spawnparticle(tracercolor,SPF_FULLBRIGHT|SPF_NOTIMEFREEZE|SPF_RELATIVE,3,18,0,0,0,0,0,0,0,0,0,0,1,-1,-1);
		Fly:
			TPEL A 1 {
				spawnDnmkFlare(pos);
				A_Spawnparticle(tracercolor,SPF_FULLBRIGHT|SPF_RELATIVE,3,random(13,15),0,0,0,0,0,0,0,0,0,0,1,-1,-1);
			}
			loop;
			
		Bounce:
			TNT1 A 0 SpawnSparkFx(pos);
			TPEL A 1 SpawnSparkFx(pos);
			goto Fly;
			
		Death:
			TNT1 A 0 A_setscale(0.1);
			TNT1 A 0 A_explode(1,60,0);
			TNT1 A 0 A_Startsound("lildead",32);
			TNT1 A 0 SpawnBounceFx(pos);
			TNT1 A 0 spawnDnmkFlare(pos,true);
			TNT1 A 0 SpawnSparkFx(pos);
			5PRK AAAA 1 { A_setscale(self.scale.x + frandom(0.025,0.075)); A_Fadeout(0.15); }
			stop;
			
	}
	
	static const color DanmkTracerCol[] = {
		"83FFF9","D083FF","83AEFF","BAEFFF","E0BAFF",
		"E9BAFF","FFBAD0","7FC9FF","C27FFF","FFFFFF"
	};
	
	void SpawnBounceFx(vector3 where)
	{
		FSpawnParticleParams DnmkBnc;
		DnmkBnc.Texture = TexMan.CheckForTexture("SHWKK0");
		DnmkBnc.Color1 = tracercolor;//"FFFFFF";
		DnmkBnc.Style = STYLE_AddStencil;
		DnmkBnc.Flags = SPF_ROLL|SPF_FULLBRIGHT;
		DnmkBnc.Vel = (0,0,0); 
		DnmkBnc.Startroll = 0;//random(0,360);
		DnmkBnc.RollVel = frandom(-3,3);
		DnmkBnc.StartAlpha = 0.80;
		DnmkBnc.Lifetime = random(7,10); 
		DnmkBnc.FadeStep = DnmkBnc.StartAlpha / DnmkBnc.Lifetime;
		DnmkBnc.Size = 32;
		DnmkBnc.SizeStep = 15;
		DnmkBnc.Pos = where;
		Level.SpawnParticle(DnmkBnc);
	}
	
	void SpawnSparkFx(vector3 where)
	{
		FSpawnParticleParams DnmkSprk;
		DnmkSprk.Texture = TexMan.CheckForTexture("5PRKA0");
		DnmkSprk.Color1 = tracercolor;//"FFFFFF";
		DnmkSprk.Style = STYLE_Add;
		DnmkSprk.Flags = SPF_ROLL|SPF_FULLBRIGHT;
		DnmkSprk.Vel = (random(-5,5),random(-5,5),random(-2,9));
		DnmkSprk.accel = (0,0,frandom(-1.75,-0.75));
		DnmkSprk.Startroll = randompick(0,90,180,270,360);
		DnmkSprk.RollVel = 0;
		DnmkSprk.StartAlpha = 1.0;
		DnmkSprk.FadeStep = 0.075;
		DnmkSprk.Size = random(8,14);
		DnmkSprk.SizeStep = -0.5;
		DnmkSprk.Lifetime = random(12,18); 
		DnmkSprk.Pos = where;
		Level.SpawnParticle(DnmkSprk);
	}
	
	void spawnDnmkFlare(vector3 position, bool bigger = false)
	{
		FSpawnParticleParams FFLAR;
		FFLAR.Texture = TexMan.CheckForTexture("5PRKA0");//("LENSA0");//("L2NBA0");
		FFLAR.Color1 = tracercolor;//"FFFFFF";
		FFLAR.Style = STYLE_ADDSTENCIL;
		FFLAR.Flags = SPF_ROLL|SPF_FULLBRIGHT;
		FFLAR.Vel = (0,0,0);
		FFLAR.Startroll = random(0,360);
		FFLAR.RollVel = frandom(-5,5);
		FFLAR.StartAlpha = 0.85;
		FFLAR.FadeStep = 0.15;
		FFLAR.Size = bigger ? random(50,69) : random(20,30);
		FFLAR.SizeStep = -5;
		FFLAR.Lifetime = bigger ? random(4,6): 1; 
		FFLAR.Pos = position;
		Level.SpawnParticle(FFLAR);
	}
	
	override void beginplay()
	{
		self.bxflip = random(0,1);
		self.byflip = random(0,1);
		A_Setroll(random(0,360));
		int c = random(0,self.DanmkTracerCol.Size()-1);
		tracercolor = self.DanmkTracerCol[c];
		super.beginplay();
	}
}
