version "4.11.3"

// Monster Drop Handler
#include "zscript/beefhandler.zs"

// Random Weapon Switch
#include "zscript/Random Weapon Switcher/ZRWSwitchMenu.zc"
#include "zscript/Random Weapon Switcher/ZRWSwitcher.zc"

// Spawners ZScript
#include "zscript/MergedSpawner.zc"
#include "zscript/Insanity's Nightmare/ChainsawSpawn.zc"
#include "zscript/Weapons/Slot-3/CSSG/CSSGEvent.zs"
#include "zscript/NewMonsterSpawner.zs"
#include "zscript/GORENEST.zs"

// Player Pawn Insanity Beef: Will this be added later?
//#include "zscript/CustomPlayerClass/INPlayer.zc"
//#include "ZScript/CustomPlayerClass/PBMeleePlayer.zc"

// Weapon Wheel Stuff
#include "zscript/Weapons/Slot-3/CSSG/CSSG_Wheel.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExt_Wheel.zs"
#include "Zscript/D2016Shotgun_Wheel.zs" //BORING GUN // SKill Issue :cacotroll:
#include "zscript/Insanity's Nightmare/IN_SpecialWheeltest.zs"

// Casings
#include "zscript/Weapons/Slot-3/CSSG/Casings.zs"
#include "zscript/Insanity's Nightmare/HASGCasings.zc"
#include "zscript/Insanity's Nightmare/IN_BulletSystem.zc"
#include "zscript/Insanity's Nightmare/IN_SpecialProjectile.zc"
#include "zscript/Insanity's Nightmare/PlasmaRifleAssaultProjectile.zc"

// Weapons & Etc (Testing)

	// CSSG Stuff Begin
#include "zscript/Weapons/Slot-3/CSSG/CSSG.zs"
#include "zscript/Weapons/Slot-3/CSSG/CSSG_Upgrades.zs"
	// CSSG Stuff End
#include "ZScript/Weapons/Slot-4/HeavySniperRifle.zs"
#include "ZScript/Weapons/Slot-6/Excavator.zs"
#include "zscript/Weapons/Slot-8/LoRCalamityBlade.zs"
	// Demonic Exterminator Stuff Begin
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExt.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtFunctions.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtAttacks.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtProj.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtProj2.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtProj3.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtStuff.zs"
	// Demonic Exterminator Stuff End

//Doorbuster
#include "zscript/Doorbuster/doorbuster.zs"
#include "zscript/Doorbuster/doorbuster_handler.zs"

