version "4.11.3"

#include "ZSCRIPT/beefhandler.zs"

// Random Weapon Switch
#include "zscript/Random Weapon Switcher/ZRWSwitchMenu.zc"
#include "zscript/Random Weapon Switcher/ZRWSwitcher.zc"

// Spawners ZScript
#include "zscript/MergedSpawner.zc"
#include "zscript/Insanity's Nightmare/ChainsawSpawn.zc"
#include "zscript/Weapons/Slot-3/CSSG/CSSGEvent.zs"
#include "zscript/NewMonsterSpawner.zs"
#include "ZSCRIPT/GORENEST.zs"

// Player Pawn Insanity Beef: Will this be added later?
//#include "zscript/CustomPlayerClass/INPlayer.zc"
//#include "ZScript/CustomPlayerClass/PBMeleePlayer.zc"

// Weapon Wheel Stuff
#include "zscript/Weapons/Slot-3/CSSG/CSSG_Wheel.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExt_Wheel.zs"
#include "Zscript/D2016Shotgun_Wheel.zs"
#include "zscript/Insanity's Nightmare/IN_SpecialWheeltest.zs"

// Casings
#include "zscript/Weapons/Slot-3/CSSG/Casings.zs"
#include "zscript/Insanity's Nightmare/HASGCasings.zc"
#include "zscript/Insanity's Nightmare/IN_BulletSystem.zc"
#include "zscript/Insanity's Nightmare/IN_SpecialProjectile.zc"
#include "zscript/Insanity's Nightmare/PlasmaRifleAssaultProjectile.zc"

// Weapons & Etc (Testing)
	// CSSG Stuff Begin
#include "zscript/Weapons/Slot-3/CSSG/CSSG.zs"
#include "zscript/Weapons/Slot-3/CSSG/CSSG_Upgrades.zs"
	// CSSG Stuff End
#include "ZScript/Weapons/Slot-4/HeavySniperRifle.zs"
#include "ZScript/Weapons/Slot-6/Excavator.zs"
#include "zscript/Weapons/Slot-8/CalamityBlade.zs"
	// Demonic Exterminator Stuff Begin
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExt.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtFunctions.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtAttacks.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtProj.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtProj2.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtProj3.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtStuff.zs"
	// Demonic Exterminator Stuff End

//Axe spawner Beef: Why do we even need this??????
class PB_AxeSpawnerInjector : PBInjector
{
	override void Init(PB_EventHandler handler)
	{
		handler.InjectSpawn('PB_SawSpawnerT1', 'PB_Axe', 255, 1);
		handler.InjectSpawn('PB_SawSpawnerT2', 'PB_Axe', 255, 1);
		handler.InjectSpawn('PB_SawSpawnerT3', 'PB_Axe', 255, 1);
		handler.InjectSpawn('PB_SawSpawnerT4', 'PB_Axe', 255, 1);
	}
}

class PB_DemontechRifleSpawnerInjector : PBInjector
{
	override void Init(PB_EventHandler handler)
	{
		handler.InjectSpawn('PB_MGSpawnerT3', 'PB_Demontech', 255, 1);
	}
}

//Doorbuster
#include "zscript/Doorbuster/doorbuster.zs"
#include "zscript/Doorbuster/doorbuster_handler.zs"

