class PBSawStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Melee"; }
	override Name GetItem() { return 'PB_Chainsaw'; }
	override string GetIcon() { return "CSAWA0"; }
	override string GetDisplayName() { return "Chainsaw"; }
	override int GetBasePrice() { return 80; }
	override string GetFlavorText() { return "VRRRRRRRRRRRRRR!"; }
}

class PBAxeStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Melee"; }
	override Name GetItem() { return 'PB_Axe'; }
	override string GetIcon() { return "AXE0A0"; }
	override string GetDisplayName() { return "Axe"; }
	override int GetBasePrice() { return 60; }
	override string GetFlavorText() { return "Heres Johnny!"; }
}

class PBPistolStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Low Cal"; }
	override Name GetItem() { return 'PB_Pistol'; }
	override string GetIcon() { return "DEGTA0"; }
	override string GetDisplayName() { return "UAC-B950 .45 Pistol"; }
	override int GetBasePrice() { return 100; }
	override string GetFlavorText() { return "Fill your enemies with tiny holes."; }
}

class PBRevolverStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Low Cal"; }
	override Name GetItem() { return 'PB_Revolver'; }
	override string GetIcon() { return "RVICA0"; }
	override string GetDisplayName() { return "UAC .500 Magnum"; }
	override int GetBasePrice() { return 110; }
	override string GetFlavorText() { return "It's high noon."; }
}

class PBSMGStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Low Cal"; }
	override Name GetItem() { return 'PB_SMG'; }
	override string GetIcon() { return "ATFLA0"; }
	override string GetDisplayName() { return "UAC17 Compact Sub-Machine Gun"; }
	override int GetBasePrice() { return 120; }
	override string GetFlavorText() { return "Low power but deadly... If you shoot for long enough."; }
}

class PBMP40Store : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Low Cal"; }
	override Name GetItem() { return 'PB_MP40'; }
	override string GetIcon() { return "AMP4A0"; }
	override string GetDisplayName() { return "Maschinenpistole 40"; }
	override int GetBasePrice() { return 120; }
	override string GetFlavorText() { return "Nothing like peak German engineering."; }
}

class PBDMRStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality High Cal"; }
	override Name GetItem() { return 'Rifle'; }
	override string GetIcon() { return "RIFLA0"; }
	override string GetDisplayName() { return "UAC-30 DMR"; }
	override int GetBasePrice() { return 140; }
	override string GetFlavorText() { return "For all your demon hunting needs."; }
}

class PBCarbineStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality High Cal"; }
	override Name GetItem() { return 'Carbine'; }
	override string GetIcon() { return "CB00Z0"; }
	override string GetDisplayName() { return "UAC-41 Carbine"; }
	override int GetBasePrice() { return 150; }
	override string GetFlavorText() { return "Fill em with holes!"; }
}

class PBMinigunStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality High Cal"; }
	override Name GetItem() { return 'PB_Minigun'; }
	override string GetIcon() { return "MG0ZA0"; }
	override string GetDisplayName() { return "UAC Mach-3 Minigun"; }
	override int GetBasePrice() { return 180; }
	override string GetFlavorText() { return "I hope you can feed this monster."; }
}

class PBNailgunStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality High Cal"; }
	override Name GetItem() { return 'PB_Nailgun'; }
	override string GetIcon() { return "NLMGF0"; }
	override string GetDisplayName() { return "UAC240 Perforator Nailgun"; }
	override int GetBasePrice() { return 190; }
	override string GetFlavorText() { return "What the fuck are you doing, this is a construction tool!"; }
}

class PBRocketLauncherStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Explosive"; }
	override Name GetItem() { return 'PB_RocketLauncher'; }
	override string GetIcon() { return "RKTLZ0"; }
	override string GetDisplayName() { return "UAC Guided Rocket Launcher"; }
	override int GetBasePrice() { return 220; }
	override string GetFlavorText() { return "Now you're packing heat. ...Are you?"; }
}

class PBSGLStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Explosive"; }
	override Name GetItem() { return 'PB_SuperGL'; }
	override string GetIcon() { return "SGL0Z0"; }
	override string GetDisplayName() { return "UAC-MGL Automatic Grenade Launcher"; }
	override int GetBasePrice() { return 240; }
	override string GetFlavorText() { return "Load types galore!"; }
}

class PBM1PlasmaStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Energy"; }
	override Name GetItem() { return 'PB_M1Plasma'; }
	override string GetIcon() { return "PLASA0"; }
	override string GetDisplayName() { return "UAC-M1 Plasma Rifle"; }
	override int GetBasePrice() { return 280; }
	override string GetFlavorText() { return "Melt your enemies!"; }
}

class PBM2PlasmaStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Energy"; }
	override Name GetItem() { return 'PB_M2Plasma'; }
	override string GetIcon() { return "M2PRA0"; }
	override string GetDisplayName() { return "UAC-M2 Heavy Plasma Rifle"; }
	override int GetBasePrice() { return 300; }
	override string GetFlavorText() { return "Melt your enemies with style!"; }
}

class PBRailgunStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Energy"; }
	override Name GetItem() { return 'PB_Railgun'; }
	override string GetIcon() { return "SRCGA0"; }
	override string GetDisplayName() { return "UAC-MKIII Railgun"; }
	override int GetBasePrice() { return 350; }
	override string GetFlavorText() { return "And now I will show you a magic trick. Watch as this Hell Knight disappears."; }
}

class PBFreezerStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Energy"; }
	override Name GetItem() { return 'PB_Freezer'; }
	override string GetIcon() { return "FRPKA0"; }
	override string GetDisplayName() { return "UAC Cryogenic Dispersion Rifle"; }
	override int GetBasePrice() { return 340; }
	override string GetFlavorText() { return "Freeze your enemies! ...And maybe your hands too."; }
}

class PBBFGStore : StoreItem
{
	override int GetType() { return SType_Weapon; }
	override string GetCategory() { return "Project Brutality Energy"; }
	override Name GetItem() { return 'PB_BFG9000'; }
	override string GetIcon() { return "RDABX0"; }
	override string GetDisplayName() { return "BFG 9000 Mark IV"; }
	override int GetBasePrice() { return 600; }
	override string GetFlavorText() { return "Because fuck your targets, fuck your shoulder, fuck their cover, and fuck you."; }
}