class QuickDetonator : Inventory {}
class GoThrowAxe : Inventory {}

class PB_RevLauncherFireCount : Inventory{Default{Inventory.MaxAmount 3;}}
extend class PB_WeaponBase
{
	States
	{
		UseEquipment:
			TNT1 A 0 A_JumpIfInventory("CantDoAction", 1, "FailOverlay");
			TNT1 A 0 A_JumpIf(health <= 0, "FailOverlay");
			TNT1 A 0 {
				A_ClearOverlays(-80, -11);
				A_ClearOverlays(-9, 80);
				// The legs were -10
				A_GunFlash("Null"); //Fixes the Minigun heat overlay oversight
				A_TakeInventory("Zoomed", 1);
				A_TakeInventory("RailgunInfrared", 1);
				A_Zoomfactor(1.0);
				A_GiveInventory("KeepLaserDeactivated",1);
				A_StopSound(CHAN_WEAPON);
				A_StopSound(CHAN_VOICE);
				A_StopSound(CHAN_6);
				A_StopSound(CHAN_7);
				A_TakeInventory("UseEquipment", 1);
				A_GiveInventory("KeepLaserDeactivated",1);
			}
			TNT1 A 0 A_JumpIfInventory ("QuickDetonator", 1, "Detonator");
			TNT1 A 0 A_JumpIfInventory ("GrabbedBarrel", 1, "IdleBarrel");
			TNT1 A 0 A_JumpIfInventory ("GrabbedFlameBarrel", 1, "IdleFlameBarrel");
			TNT1 A 0 A_JumpIfInventory ("GrabbedIceBarrel", 1, "IdleIceBarrel");
			TNT1 A 0 A_JumpIfInventory("FragGrenadeSelected", 1, "ThrowGrenade");
			TNT1 A 0 A_JumpIfInventory("ProximityMineSelected", 1, "ThrowMine");
			TNT1 A 0 A_JumpIfInventory("ElecPodSelected", 1, "ThrowElecPod");
			TNT1 A 0 A_JumpIfInventory("StunGrenadeSelected", 1, "ThrowStun");
			TNT1 A 0 A_JumpIfInventory("LeechSelected", 1, "ThrowLeech");
			TNT1 A 0 A_JumpIfInventory("ShieldSelected", 1, "ThrowShieldGrenade");
			TNT1 A 0 A_JumpIfInventory("VoidGrenadeSelected", 1, "ThrowVoidGrenade");
			TNT1 A 0 A_JumpIfInventory("SwarmerSelected", 1, "ThrowSwarmer");
			TNT1 A 0 A_JumpIfInventory("LaserChargeSelected", 1, "ThrowLaserCharge");
			TNT1 A 0 A_JumpIfInventory("AcidChargeSelected", 1, "ThrowAcidCharge");
			TNT1 A 0 A_JumpIfInventory("DetonatorSelected", 1, "Detonator");
			TNT1 A 0 A_JumpIfInventory("AxeSelected", 1, "ThrowAxe");
			//TNT1 A 0 A_JumpIfInventory("RevGunSelected", 1, "FireRevGun");
			//More stuff to come.....
			Goto GoingToReady;
		WheelCancelEquipment:
			TNT1 A 0
				{
				A_SetInventory("WW_ProximityMineSelected",0);
				A_SetInventory("WW_ElecPodSelected",0);
				A_SetInventory("WW_StunGrenadeSelected",0);
				A_SetInventory("WW_LeechSelected",0);
				A_SetInventory("WW_FragGrenadeSelected",0);
				A_SetInventory("WW_RevGunSelected",0);
				A_SetInventory("WW_ShieldSelected",0);
				A_SetInventory("WW_VoidGrenadeSelected",0);
				A_SetInventory("WW_SwarmerSelected",0);
				A_SetInventory("WW_LaserChargeSelected",0);
				A_SetInventory("WW_AcidChargeSelected",0);
				A_SetInventory("WW_DetonatorSelected",0);
				A_SetInventory("WW_AxeSelected",0);
				A_SetInventory("CantWeaponSpecial",0);
				}
			goto Equipment_Toggle_Handler_Overlay;
		SwitchEquipment:	
			TNT1 A 0 A_TakeInventory("ToggleEquipment", 1);
			TNT1 A 0 {
				if(CountInv("WW_ProximityMineSelected") && CountInv("ProximityMineSelected") >=1)
					{A_Print("Equipment already selected: Proximity Mine"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_ElecPodSelected") && CountInv("ElecPodSelected") >=1)
					{A_Print("Equipment already selected: Electric Pod"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_StunGrenadeSelected") && CountInv("StunGrenadeSelected") >=1)
					{A_Print("Equipment already selected: Stun Grenade"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_LeechSelected") && CountInv("LeechSelected") >=1)
					{A_Print("Equipment already selected: Leech"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_FragGrenadeSelected") && CountInv("FragGrenadeSelected") >=1)
					{A_Print("Equipment already selected: Frag Grenade"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_RevGunSelected") && CountInv("RevGunSelected") >=1)
					{A_Print("Equipment already selected: Revenant Launcher"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_ShieldSelected") && CountInv("ShieldSelected") >=1)
					{A_Print("Equipment already selected: Shield Grenade"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_VoidGrenadeSelected") && CountInv("VoidGrenadeSelected") >=1)
					{A_Print("Equipment already selected: Void Grenade"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_SwarmerSelected") && CountInv("SwarmerSelected") >=1)
					{A_Print("Equipment already selected: Swarm Pod"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_LaserChargeSelected") && CountInv("LaserChargeSelected") >=1)
					{A_Print("Equipment already selected: Laser Charge"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_AcidChargeSelected") && CountInv("AcidChargeSelected") >=1)
					{A_Print("Equipment already selected: Acid Charge"); return ResolveState("WheelCancelEquipment");}	
				if(CountInv("WW_DetonatorSelected") && CountInv("DetonatorSelected") >=1)
					{A_Print("Equipment already selected: Detonator"); return ResolveState("WheelCancelEquipment");}	
				if(CountInv("WW_AxeSelected") && CountInv("AxeSelected") >=1)
					{A_Print("Equipment already selected: Axe"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_ProximityMineSelected") >=1)
					{
					if(CountInv("PB_ProxMineAmmo") <=0)
						{A_Print("No Mines Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_ElecPodSelected") >=1)
					{
					if(CountInv("ElecPodAmmo") <=0)
						{A_Print("No Electric Pod Available"); return ResolveState("WheelCancelEquipment");}
					}	
				if(CountInv("WW_StunGrenadeSelected") >=1)
					{
					if(CountInv("PB_StunGrenadeAmmo") <=0)
						{A_Print("No Stun Grenades Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_LeechSelected") >=1)
					{
					if(CountInv("HasLeech") <=0)
						{A_Print("No Leech Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_RevGunSelected") >=1)
					{
					if(CountInv("PB_QuickLauncherAmmo") <=0)
						{A_Print("No Revenant Launcher Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_FragGrenadeSelected") >=1)
					{
					if(CountInv("PB_GrenadeAmmo") <=0)
						{A_Print("No Frag Grenades Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_ShieldSelected") >=1)
					{
					if(CountInv("ShieldGrenadeAmmo") <=0)
						{A_Print("No Shield Grenades Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_VoidGrenadeSelected") >=1)
					{
					if(CountInv("VoidGrenadeAmmo") <=0)
						{A_Print("No Void Grenades Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_SwarmerSelected") >=1)
					{
					if(CountInv("SwarmerAmmo") <=0)
						{A_Print("No Swarm Pod Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_LaserChargeSelected") >=1)
					{
					if(CountInv("LaserChargeAmmo") <=0)
						{A_Print("No Laser Charge Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_AcidChargeSelected") >=1)
					{
					if(CountInv("AcidChargeAmmo") <=0)
						{A_Print("No Acid Charge Available"); return ResolveState("WheelCancelEquipment");}	
					}	
				if(CountInv("WW_DetonatorSelected") >=1)
					{
					if(CountInv("DetonatorAmmo") <=0)
						{A_Print("No Detonator Available"); return ResolveState("WheelCancelEquipment");}
					}	
				if(CountInv("WW_AxeSelected") >=1)
					{
					if(CountInv("PB_Axe") <=0)
						{A_Print("No Axe Available"); return ResolveState("WheelCancelEquipment");}
					}
				return ResolveState(null);
				}
			TNT1 A 0 
				{
					if(CountInv("WW_ProximityMineSelected") >=1)
						{ 
							A_Print("Equipment Selected: Proximity Mine"); 
							A_SetInventory("ProximityMineSelected",1);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_ElecPodSelected") >=1)
						{ 
							A_Print("Equipment Selected: Electric Pod"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",1);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_StunGrenadeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Stun Grenade"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",1);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_LeechSelected") >=1)
						{ 
							A_Print("Equipment Selected: Leech"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",1);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_RevGunSelected") >=1)
						{ 
							A_Print("Equipment Selected: Revenant Launcher"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",1);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("REVUP", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_FragGrenadeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Frag Grenade"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",1);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_ShieldSelected") >=1)
						{ 
							A_Print("Equipment Selected: Shield Grenade"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",1);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}	
					if(CountInv("WW_VoidGrenadeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Void Grenade"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",1);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_SwarmerSelected") >=1)
						{ 
							A_Print("Equipment Selected: Swarm Pod"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",1);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}				
					if(CountInv("WW_LaserChargeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Laser Charge"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",1);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_AcidChargeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Acid Charge"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",1);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}	
					if(CountInv("WW_DetonatorSelected") >=1)
						{ 
							A_Print("Equipment Selected: Detonator"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",1);
							A_SetInventory("AxeSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_AxeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Axe"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("DetonatorSelected",0);
							A_SetInventory("AxeSelected",1);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}		
				return ResolveState(null);
				}
			goto Equipment_Toggle_Handler_Overlay;
		
		//Axe
		ThrowAxe:
			TNT1 A 0 {
				A_WeaponOffset(0,32);
				A_SetRoll(0);
				PB_HandleCrosshair(90);
			}
			TNT1 A 0 A_SetInventory("PB_LockScreenTilt",1);
			TNT1 A 0 A_JumpIfInventory("PB_Axe", 1, 2);
			TNT1 A 0 A_Print("No Axe left");
			Goto GoingToReady;
			TNT1 A 0 A_Overlay(799,"FlashPunching");
			AX11 ABCDEF 0;
			AX12 ABCDEF 0;
			AX13 ABCDEF 0;
			TNT1 A 0 {
				A_PlaySound("AXSWING");
				A_SetRoll(0);
			}
			AX10 A 1 {
				if (CountInv("PowerGreenBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX13"); }
				if (CountInv("PowerBlueBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX12"); }
				if (CountInv("PowerBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX11"); }
				A_Setroll(roll-1.0, SPF_INTERPOLATE);
				A_SetAngle(angle+0.5, SPF_INTERPOLATE);
				
			}
			AX10 BC 1 {
				if (CountInv("PowerGreenBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX13"); }
				if (CountInv("PowerBlueBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX12"); }
				if (CountInv("PowerBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX11"); }
				A_Setroll(roll-1.0, SPF_INTERPOLATE);
				A_SetAngle(angle+0.5, SPF_INTERPOLATE);
				if (JustPressed(BT_USER1)) A_GiveInventory("GoThrowAxe", 1);
			}
			TNT1 A 0 A_JumpIfInventory("GoThrowAxe", 1, "ThrowAxe2");
			TNT1 A 0 {
				if (CountInv("PB_PowerStrength") >= 1 ) {
					A_Saw("", "", 30, "AxePuffs", 0, 120, 0,16);
					A_FireCustomMissile("AxeAttack", 0, 0, 0, 0);
					A_FireCustomMissile("AxeAttack", 0, 0, 0, 0);
				}
				else {
					A_Saw("", "", 15, "AxePuffs", 0, 120, 0,16);
					A_FireCustomMissile("AxeAttack", 0, 0, 0, 0);
				}
			
			}
			AX10 D 1 {
				if (CountInv("PowerGreenBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX13"); }
				if (CountInv("PowerBlueBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX12"); }
				if (CountInv("PowerBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX11"); }
				A_Setroll(roll-1.0, SPF_INTERPOLATE);
				A_SetAngle(angle+0.5, SPF_INTERPOLATE);
			}
			AX10 EF 1 {
				if (CountInv("PowerGreenBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX13"); }
				if (CountInv("PowerBlueBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX12"); }
				if (CountInv("PowerBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX11"); }
				A_Setroll(roll-1.0, SPF_INTERPOLATE);
				A_SetAngle(angle+0.5, SPF_INTERPOLATE);
				if (JustPressed(BT_USER1)) A_GiveInventory("GoThrowAxe", 1);
			}
			TNT1 A 0 A_JumpIfInventory("GoThrowAxe", 1, "ThrowAxe2");
			TNT1 AAA 1 {
				A_Setroll(roll+1.0, SPF_INTERPOLATE);
				A_SetAngle(angle-0.5, SPF_INTERPOLATE);
			}
			TNT1 AAA 1 {
				A_Setroll(roll+1.0, SPF_INTERPOLATE);
				A_SetAngle(angle-0.5, SPF_INTERPOLATE);
				return A_DoPBWeaponAction;
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		ThrowAxe2:
			TNT1 A 1;
			AX31 ABCDEFGHIJKLMNOPQ 0;
			AX32 ABCDEFGHIJKLMNOPQ 0;
			AX33 ABCDEFGHIJKLMNOPQ 0;
			TNT1 A 0 A_PlaySound("AXTHROW");
			AX30 HIJKLM 1 {
				if (CountInv("PowerGreenBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX33"); }
				if (CountInv("PowerBlueBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX32"); }
				if (CountInv("PowerBloodOnVisor") >= 1 ) { A_SetWeaponSprite("AX31"); }
				A_Setroll(roll+0.5, SPF_INTERPOLATE);
			}
			TNT1 A 0 {
			if(CountInv("PowerGreenBloodOnVisor") >=1 ) {A_FireCustomMissile("ThrownAxe_Green", 0, 0, 0, 0);}
			else if (CountInv("PowerBlueBloodOnVisor") >=1 ) {A_FireCustomMissile("ThrownAxe_Blue", 0, 0, 0, 0);}
            else if (CountInv("PowerBloodOnVisor") >=1 ) {A_FireCustomMissile("ThrownAxe_Red", 0, 0, 0, 0);}
            else {
			A_FireCustomMissile("ThrownAxe", 0, 0, 0, 0);
			}
			}
			TNT1 A 0 A_TakeInventory("PB_Axe", 1);
			TNT1 A 0 A_TakeInventory("GoThrowAxe", 1);
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		
		//Electric Pod
		ThrowElecPod:	
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("ElecPodAmmo", 1, 2);
			TNT1 A 0 A_Print("No Electrid Pods left");
			Goto GoingToReady;
			XPFF FEDCBA 1;
			XPFS B 4 A_StartSound("weapons/pbarm", 2);
			XHFF A 0 {
				A_StartSound("MINE002", 3);
				A_ThrowGrenade("ElectricPodSet",4,11,1,0);
				A_TakeInventory("ElecPodAmmo", 1);
			}
			XHFF MNOPQRSTUVWXYZ 1;
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
			
		//Acid Charge
		ThrowAcidCharge:
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("AcidChargeAmmo", 1, 2);
			TNT1 A 0 A_Print("No Acid Charge left");
			Goto GoingToReady;
			
			REMT ABCD 1;
			REMT EFG 1{
			// Check during animation — if player presses again, flag UseEquipment
			if (JustPressed(BT_USER1)) A_GiveInventory("QuickDetonator", 1);
			}
			REMT HIJKLMNOPQ 1{
			if (JustPressed(BT_USER1)) A_GiveInventory("QuickDetonator", 1);
			}
			// Before firing projectile, see if player triggered alt behavior
			TNT1 A 0 A_JumpIfInventory("QuickDetonator", 1, "Detonator");
			
			//REMT ABCDEFGHIJKLMNOPQ 1;
			THRO ABCD 1;
			TNT1 A 0 {
				A_PlaySound("charge/place/remote", 3);
				A_FireCustomMissile("ThrownAcidCharge",0,0,0,-1);
				A_TakeInventory("AcidChargeAmmo", 1);
			}
			THRO EEEEFGHI 1;
		
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
			
		//Laser Charge
		ThrowLaserCharge:
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("LaserChargeAmmo", 1, 2);
			TNT1 A 0 A_Print("No Laser Charge left");
			Goto GoingToReady;
			
			LSRC ABCD 1;
			LSRC EFG 1{
			// Check during animation — if player presses again, flag UseEquipment
			if (JustPressed(BT_USER1)) A_GiveInventory("QuickDetonator", 1);
			}
			LSRC HIJKLMNOPQ 1{
			if (JustPressed(BT_USER1)) A_GiveInventory("QuickDetonator", 1);
			}
			// Before firing projectile, see if player triggered alt behavior
			TNT1 A 0 A_JumpIfInventory("QuickDetonator", 1, "Detonator");
			
			//LSRC ABCDEFGHIJKLMNOPQ 1;
			THRO ABCD 1;
			TNT1 A 0 {
				A_PlaySound("charge/place/laser", 3);
				A_FireCustomMissile("ThrownLaserCharge",0,0,0,-1);
				A_TakeInventory("LaserChargeAmmo", 1);
			}
			THRO EEEEFGHI 1;
			
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
			
		//Swarm Pod
		ThrowSwarmer:
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("SwarmerAmmo", 1, 2);
			TNT1 A 0 A_Print("No Swarm Pods left");
			Goto GoingToReady;
		
			SWRM ABCD 1;
			SWRM EFG 1{
			// Check during animation — if player presses again, flag UseEquipment
			if (JustPressed(BT_USER1)) A_GiveInventory("QuickDetonator", 1);
			}
			SWRM HIJLMNOPQ 1{
			if (JustPressed(BT_USER1)) A_GiveInventory("QuickDetonator", 1);
			}
			// Before firing projectile, see if player triggered alt behavior
			TNT1 A 0 A_JumpIfInventory("QuickDetonator", 1, "Detonator");
			
			//SWRM ABCDEFGHIJLMNOPQ 1;
			THRO ABCD 1;
			TNT1 A 0 {
				A_PlaySound("charge/place/swarm", 3);
				A_FireCustomMissile("ThrownSwarmCharge",0,0,0,-1);
				A_TakeInventory("SwarmerAmmo", 1);
			}
			THRO EEEEFGHI 1;

			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
			
		//ShieldGrenade
		ThrowShieldGrenade:
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("ShieldGrenadeAmmo", 1, 2);
			TNT1 A 0 A_Print("No Shield Grenades left");
			Goto GoingToReady;
			
			SHIG CDEFGH 1;
			TNT1 A 0 A_StartSound("StunGrenadeArm", 2);
			SHIG IJKLMNOP 1;
			
			GRTH OPQ 1 A_StartSound("THRGRN", 1);
			TNT1 A 0 A_TakeInventory("ShieldGrenadeAmmo", 1);
			GRTH Q 1 A_FireProjectile("ThrownShieldGrenade",0,0,0,0,0,0);
			GRTH RSTU 1;
			
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		
		//VoidGrenade
		ThrowVoidGrenade:
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("VoidGrenadeAmmo", 1, 2);
			TNT1 A 0 A_Print("No Void Grenades left");
			Goto GoingToReady;
			TNT1 A 0 A_Giveinventory("PlayerIsThrowingAGrenade",1);
			
			VGRN NOPQ 1;
			TNT1 A 0 A_StartSound("grenade/arm/void", 2);
			VGRN VWXCD 1;
			
			GRTH OPQ 1 A_StartSound("THRGRN", 1);
			TNT1 A 0 A_TakeInventory("VoidGrenadeAmmo", 1);
			GRTH Q 1 A_FireProjectile("ThrownVoidGrenade",0,0,0,0,0,0);
			GRTH RSTU 1;
			
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
				A_TakeInventory("PlayerIsThrowingAGrenade", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		
		//Detonator
		Detonator:
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				A_PlaySound("charge/detonator", 3);
				A_Overlay(799,"FlashPunching");
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			DETO ABCD 1;
			TNT1 A 0 A_GiveInventory("RemoteChargeDetonator",1);
			DETO E 6;
			TNT1 A 0 A_TakeInventory("RemoteChargeDetonator",1);
			DETO DCBA 1;
			
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
				A_TakeInventory("QuickDetonator", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		
		//Leech
		LeechBeam:
			SYNP WXYZWXYZWXYZ 1 BRIGHT;
			SYNP WXYZWXYZWXYZ 1 BRIGHT;
			SYNP WXYZWXYZWXYZ 1 BRIGHT;
			SYNP WXYZWXYZWXYZ 1 BRIGHT;
			stop;
		ThrowLeech:
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("PB_Dtech", 100, 2);
			TNT1 A 0 A_Print("Need more Demon Energy");
			Goto GoingToReady;
			TNT1 A 1 {A_WeaponOffset(-8,108);A_StartSound("SiphonGrowl");}
			SYNP G 1 A_WeaponOffset(-7,98);
			SYNP H 1 A_WeaponOffset(-6,88);
			SYNP H 1 A_WeaponOffset(-5,78);
			SYNP I 1 A_WeaponOffset(-4,68);
			SYNP I 1 A_WeaponOffset(-3,58);
			SYNP J 1 A_WeaponOffset(-2,48);
			SYNP J 1 A_WeaponOffset(-1,38);
			SYNP GHIHIJGJIHG 2 A_WeaponOffset(0,32);
			SYNP G 1 A_WeaponOffset(-2,40);
			SYNP H 1 A_WeaponOffset(-4,50);
			SYNP I 1 A_WeaponOffset(-6,60);
			SYNP J 1 A_WeaponOffset(-8,70);
			SYNP KLMNO 1 A_WeaponOffset(0,32);
			TNT1 A 0 A_Overlay(-5, "LeechBeam");
			TNT1 A 0 A_StartSound("SiphonActive", 3);
			TNT1 A 0 A_TakeInventory("PB_Dtech", 100);
			SYNP ABCDEFABCDEFABCDEFABCDEF 2 A_FireBullets(0, 0, -1, 3, "SiphonPuff", FBF_NORANDOM);
			SYNP ONMLK 1;
			TNT1 A 0 {
				A_WeaponOffset(0,32);
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
			
		//Stun
		ThrowStun:
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("PB_StunGrenadeAmmo", 1, 2);
			TNT1 A 0 A_Print("No Stun Grenades left");
			Goto GoingToReady;
			STNG BCDEF 1;
			STNG F 1 Offset(-2,34);
			TNT1 A 0 A_StartSound("StunGrenadeArm", 2);
			STNG GIJJJIHGKLMNOP 1;
			
			HND1 I 1 A_StartSound("THRGRN", 1);
			TNT1 A 0 A_TakeInventory("PB_StunGrenadeAmmo", 1);
			HND1 J 1 A_FireProjectile("ThrownStunGrenade",0,0,0,0,0,0);
			HND1 KLMNOPQ 1;
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
			
		//RevGun	
		FireRevGun:
			TNT1 A 0 {
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("PB_QuickLauncherAmmo", 1, 2);
			TNT1 A 0 A_Print("No Revenant Launcher Ammo");
			stop;
			TNT1 A 0 {A_StartSound("revup", CHAN_AUTO, CHANF_OVERLAP);}
			RVCA ABCDEFGHIJK 1;
			RVCF AB 1;
		FiringRevGun:
			TNT1 A 0 {if (player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))){return ResolveState("FireRevGunDeselect");} return ResolveState(null);}
			RVCF C 1 {
				A_AlertMonsters();
				A_TakeInventory("PB_QuickLauncherAmmo", 1);
					/*
					if(!FindInventory("PB_RevLauncherFireCount")){A_AlertMonsters();}
					if(CountInv("PB_RevLauncherFireCount")<3){A_GiveInventory("PB_RevLauncherFireCount",1);
					}else{A_TakeInventory("PB_QuickLauncherAmmo", 1);A_SetInventory("PB_RevLauncherFireCount",0);}
					*/
				A_FireProjectile("Alerter",0,0,-1,0);
				A_StartSound("hellishmissle/fire",CHAN_AUTO, CHANF_OVERLAP);
			}
			RVCF D 1 BRIGHT A_FireProjectile("DoomerRevenantSeeker3", random(4,-4), 0, -8, 0);
			RVCF E 1 BRIGHT {
				A_StartSound("hellishmissle/fire", CHAN_AUTO, CHANF_OVERLAP);
				A_FireProjectile("ShakeYourAss",0,0,0,0,0,0);
				A_FireProjectile("DoomerRevenantSeeker2", random(4,-4), 0, 8, 0);
			}
			RVCF FG 1 BRIGHT {if (player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))){return ResolveState("FireRevGunDeselect");} return ResolveState(null);}
			RVCF HI 1 {if (player.FindPSprite(PSP_WEAPON) && InStateSequence(player.FindPSprite(PSP_WEAPON).curstate, ResolveState("Deselect"))){return ResolveState("FireRevGunDeselect");} return ResolveState(null);}
			TNT1 A 0 A_JumpIf(CountInv("PB_QuickLauncherAmmo") > 0 && PressingUser1(), "FiringRevGun");
			goto FireRevGunFinish;
		FireRevGunFinish:
			RVCF BA 1 {
				if(CountInv("PB_QuickLauncherAmmo") < 1 && PressingUser1()){
					A_Print("No Revenant Launcher Ammo");
				}
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			RVCA K 1 A_StartSound("revcyc", CHAN_AUTO, CHANF_OVERLAP);
			RVCA JIHGFEDCB 1;
			RVCA A 1 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			stop;
		FireRevGunDeselect:
			RVCA H 1 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
				A_StartSound("revcyc", CHAN_AUTO, CHANF_OVERLAP);
			}
			RVCA FDCB 1;
			stop;
			
		//Grenade	
		ThrowGrenade:
			TNT1 A 0 {
				A_StopSound(6);
				A_StopSound(CHAN_VOICE);
				A_ZoomFactor(1.0);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("PB_GrenadeAmmo", 1, 2);
			TNT1 A 0 A_Print("No Grenades left");
			Goto GoingToReady;
			TNT1 A 0 A_Giveinventory("PlayerIsThrowingAGrenade",1);
			
			HNDF ABCDE 1 A_SetRoll(roll+2.0, SPF_INTERPOLATE);
			HNDF FGHI 1 {
				A_SetRoll(roll+2.0, SPF_INTERPOLATE);
				if(JustPressed(BT_USER1)) A_GiveInventory("UseEquipment",1);
				}
			TNT1 A 0 A_StartSound("OPNGRN",0);
			HNDF JKLMNOPQR 1 {
				A_SetRoll(roll+2.0, SPF_INTERPOLATE);
				if(JustPressed(BT_USER1)) A_GiveInventory("UseEquipment",1);
				}
				
			TNT1 A 0 A_JumpIfInventory("UseEquipment", 1, "TossGrenade");
			TNT1 A 1 A_SetRoll(roll-18.0);
			HND1 I 1 A_StartSound("THRGRN",0);
			HND1 J 1 {
				A_FireProjectile("PB_ThrownGrenade",0,0,0,0,0,0);
				A_TakeInventory("PB_GrenadeAmmo", 1);
				A_FireProjectile("Alerter",0,0,0,0,0,0);
			}
			HND1 KLMNOPQ 1 A_SetRoll(roll-5.0);
			TNT1 A 0 {
			A_SetRoll(0, SPF_INTERPOLATE);
			A_TakeInventory("UseEquipment", 1);
			A_TakeInventory("ToggleEquipment", 1);
			A_TakeInventory("PlayerIsThrowingAGrenade", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
		TossGrenade:
			TNT1 A 1;
			HND1 RSTU 1 A_SetRoll(roll-1.5, SPF_INTERPOLATE);
			TNT1 A 0 {
				A_StartSound("THRGRN", 1);
				A_TakeInventory("PB_GrenadeAmmo", 1);
				A_FireProjectile("Alerter",0,0,0,0,0,0);
				A_FireProjectile("ThrownGrenade15", 0,0,0,-2,0,3);
			}
			HND1 VWXY 1 A_SetRoll(roll-1.5, SPF_INTERPOLATE);
			TNT1 A 0 {
				A_SetRoll(0);
				A_TakeInventory("PB_LockScreenTilt",1);
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
				A_TakeInventory("PlayerIsThrowingAGrenade", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
			
		//Mine	
		ThrowMine:
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				A_TakeInventory("ADSMode", 1);
				A_TakeInventory("UseEquipment", 1);
			}
			TNT1 A 0 A_JumpIfInventory("PB_ProxMineAmmo", 1, 2);
			TNT1 A 0 A_Print("No Land Mines left");
			Goto GoingToReady;
			XPFF FEDCBA 1;
			XPFS B 4 A_StartSound("weapons/pbarm", 2);
			XHFF A 0 {
				A_StartSound("MINE002", 3);
				A_ThrowGrenade("ThrownProxMine",4,11,1,0);
				A_TakeInventory("PB_ProxMineAmmo", 1);
			}
			XHFF MNOPQRSTUVWXYZ 1;
			TNT1 A 0 {
				A_TakeInventory("UseEquipment", 1);
				A_TakeInventory("ToggleEquipment", 1);
			}
			TNT1 A 0 A_JumpIf(PressingUser1(), "UseEquipment");
			Goto GoingToReady2;
	}
}